# -*- coding: utf-8 -*-
"""Juego_Derivadas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WVHKOYeDx9WuyBEnlDfCUlnep-yjI3LC
"""

"""
JUEGO DERIVADAS
Leonardo Paredes
"""

import random

print("""
MENU
0. Salir
1. Derivada Simple
2. Derivada por producto
3. Derivada por cociente
4. Derivadas parciales
""")

# ---------- FUNCIONES BASE ----------

def generar_termino():
    coef = random.randint(1, 10)
    letra = random.choice(["x", "y", "z"])
    exp = random.randint(1, 7)
    return coef, letra, exp

def termino_a_str(t):
    coef, letra, exp = t
    if exp == 1:
        return f"{coef}{letra}"
    else:
        return f"{coef}{letra}^{exp}"

def derivar_termino(t):
    coef, letra, exp = t
    nuevo_coef = coef * exp
    nuevo_exp = exp - 1

    if nuevo_exp == 0:
        return f"{nuevo_coef}"
    elif nuevo_exp == 1:
        return f"{nuevo_coef}{letra}"
    else:
        return f"{nuevo_coef}{letra}^{nuevo_exp}"

def derivar_termino_parcial(t, variable):
    coef, letra, exp = t
    if letra != variable:
        return "0"

    nuevo_coef = coef * exp
    nuevo_exp = exp - 1

    if nuevo_exp == 0:
        return f"{nuevo_coef}"
    elif nuevo_exp == 1:
        return f"{nuevo_coef}{letra}"
    else:
        return f"{nuevo_coef}{letra}^{nuevo_exp}"

# ---------- GENERADOR DE PROBLEMAS ----------

def generar_problema(opcion):

    if opcion == 1:
        print("Regla de potencia: d/du (u^n) = n * u^(n-1)")
        t = generar_termino()
        pregunta = termino_a_str(t)
        respuesta = derivar_termino(t)
        return pregunta, respuesta

    elif opcion == 2:
        print("Regla del producto: (uv)' = u'v + uv'")
        t1 = generar_termino()
        t2 = generar_termino()

        u = termino_a_str(t1)
        v = termino_a_str(t2)

        du = derivar_termino(t1)
        dv = derivar_termino(t2)

        pregunta = f"({u})({v})"
        respuesta = f"({du})({v}) + ({u})({dv})"


        return pregunta, respuesta

    elif opcion == 3:
        print("Regla del cociente: (u/v)' = (u'v - uv') / v^2")
        t1 = generar_termino()
        t2 = generar_termino()

        u = termino_a_str(t1)
        v = termino_a_str(t2)

        du = derivar_termino(t1)
        dv = derivar_termino(t2)

        pregunta = f"({u})/({v})"
        respuesta = f"(({du})({v}) - ({u})({dv})) / ({v})^2"


        return pregunta, respuesta

    elif opcion == 4:
         print("Derivadas parciales: ∂/∂x, ∂/∂y o ∂/∂z")
         t = generar_termino()
         variable = random.choice(["x", "y", "z"])
         pregunta = f"∂/∂{variable} ({termino_a_str(t)})"
         respuesta = derivar_termino_parcial(t, variable)
         return pregunta, respuesta


correctas = 0
errores = 0
while True:

    opcion = input("Ingresa una opcion: ")

    if opcion == "0":
        print("Hasta pronto!")
        break

    if opcion not in ["1", "2", "3", "4"]:
        print("Opcion no valida")
        continue

    pregunta, correcta = generar_problema(int(opcion))
    print("Funcion:", pregunta)

    while True:
        respuesta = input("Derivada: ").replace(" ", "")
        if respuesta == correcta.replace(" ", ""):
            print("Correcto!\n")
            correctas += 1
            print("Respuestas correctas: ", correctas)
            break


        else:
            print("Incorrecta, intenta nuevamente")
            errores += 1
            if errores == 3:
                print("Perdiste!")
                break